apiVersion: apps/v1
kind: Deployment
metadata:
  name: funnychar-deployment
  labels:
    app: funnychar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: funnychar
  template:
    metadata:
      labels:
        app: funnychar
    spec:
      containers:
      - name: funnychar-container
        image: <YOUR_IMAGE_TAG>
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: sqlite:///./test.db
        - name: REBYTE_API_KEY
          value: <YOUR_REBYTE_API_KEY>
        - name: OPENAI_API_KEY
          value: <YOUR_OPENAI_API_KEY>
        - name: ANTHROPIC_API_KEY
          value: <YOUR_ANTHROPIC_API_KEY>
        - name: ANYSCALE_ENDPOINT_API_KEY
          value: <YOUR_ANYSCALE_API_KEY>
        - name: SPEECH_TO_TEXT_USE
          value: LOCAL_WHISPER
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: <YOUR_GOOGLE_CREDENTIALS_FILE_NAME>
        - name: ELEVEN_LABS_API_KEY
          value: <YOUR_ELEVEN_LABS_API_KEY>
        - name: ELEVEN_LABS_USE_V2
          value: true
        - name: GCP_STORAGE_URL
          value: <YOUR_GCP_STORAGE_URL>
        - name: GCP_STORAGE_BUCKET_NAME
          value: <YOUR_GCP_STORAGE_BUCKET_NAME>
---
apiVersion: v1
kind: Service
metadata:
  name: funnychar-service
  annotations:
spec:
  type: LoadBalancer
  selector:
    app: funnychar
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
